export const continueWatchingActionTypes = {
  ADD_RECENTLY_WATCHED: 'CONTINUE_WATCHING/ADD_RECENTLY_WATCHED',
  ADD_RECENTLY_WATCHED_SUCCESS: 'CONTINUE_WATCHING/ADD_RECENTLY_WATCHED_SUCCESS',
  ADD_RECENTLY_WATCHED_FAILURE: 'CONTINUE_WATCHING/ADD_RECENTLY_WATCHED_FAILURE',
  SET_RECENTLY_WATCHED: 'CONTINUE_WATCHING/SET_RECENTLY_WATCHED',
};
